In [1]:
import numpy as np

In [6]:
z = np.array([1,2,3,4,5,6])
z

array([1, 2, 3, 4, 5, 6])

In [7]:
z.reshape(-1,6)

array([[1, 2, 3, 4, 5, 6]])

In [8]:
z.reshape(-1,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
z[1]

2